OBJS = HACKARGV.OBJ,MISC.OBJ,PIPE.OBJ,ESCTRANS.OBJ,GLOB.OBJ

*.OBJ:	*.C
	gcc/noopt/debug $<

all: TEST.EXE ECHO.EXE

TEST.EXE: TEST.OBJ,$(OBJS)
	link TEST.OBJ,$(OBJS),sys$input/opt
	gnu_cc:[000000]gcclib/lib $
	sys$share:vaxcrtl/share $

ECHO.EXE: ECHO.OBJ,$(OBJS)
	link ECHO.OBJ,$(OBJS),sys$input/opt
	gnu_cc:[000000]gcclib/lib $
	sys$share:vaxcrtl/share $
